---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: build
  image: dankamongmen/unstable_builder:2019-12-18
  commands:
    - apt-get update
    - apt-get -y remove man-db
    - apt-get -y dist-upgrade
    - apt-get -y install devscripts git-buildpackage locales
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
    - locale-gen
    - mk-build-deps --install -t'apt-get -y'
    - autoreconf -fis
    - ./configure
    - make
    - env LANG="en_US.UTF-8" make check
---
kind: pipeline
type: docker
name: debian-stable

steps:
- name: build
  image: library/debian:stable
  commands:
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
    - apt-get update
    - apt-get -y remove man-db
    - apt-get -y dist-upgrade
    - apt-get -y install devscripts git-buildpackage locales
    - echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
    - locale-gen
    - mk-build-deps --install -t'apt-get -y'
    - autoreconf -fis
    - ./configure
    - make
    - env LANG="en_US.UTF-8" make check
